/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class My */

#ifndef _Included_My
#define _Included_My
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     My
 * Method:    printmsg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_My_printmsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
